version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    restart: always
    networks:
      - network_production
  wp_php_production:
    container_name: php_production
    build: .
    networks:
      - network_production
    restart: always
    volumes:
      - ./wp-content/uploads/:/var/www/html/wp-content/uploads/
    depends_on:
      - wp_mysql_production
  wp_mysql_production:
    container_name: mysql_wp_production
    image: mysql:8.0.29
    restart: always
    env_file:
      - ./mysql.env
    volumes:
      - /data/production/demo-wp-mysql:/var/lib/mysql
    networks:
      - network_production
    ports:
      - 3306:3306
  nginx:
    image: nginx:alpine
    hostname: chatZi-ngnix
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs/Cloudflare.cert:/etc/nginx/certs/greenspire.store.crt
      - ./certs/Cloudflare.key:/etc/nginx/certs/greenspire.store.key
    depends_on:
      - wp_php_production
    networks:
      - network_production
networks:
  network_production:
    name: wordpress_network_production

